name: Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Run tests
      run: npm test
    
    - name: Display test summary
      if: always()
      run: |
        echo "=== Test Results Summary ==="
        if [ -f "test-results/vitest-results.json" ]; then
          echo "Test results saved to test-results/vitest-results.json"
          echo "View detailed results in the Test Results tab above"
        else
          echo "No test results file found"
        fi
        echo "============================="
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: test-results/
        retention-days: 30